#!/usr/bin/env bash

echo "$$" > /var/run/myscript.pid

exit1() {
    rm /var/run/myscript.pid
    exit
}

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && exit1' SIGTERM
    trap 'exit1' SIGQUIT
done
