#!/usr/bin/env bash
# script that configures the container to fit the requirements
# nginx must be running as nginx user
# listening on all active IPs on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
